spring:
  application:
    name: ecommerce-order-management

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_order_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    repair-on-migrate: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 900000          # 15 minutes
      refresh-expiration: 604800000  # 7 days (future use)

server:
  port: 8080

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE


springdoc:
  api-docs:
    path: /v3/api-docs          # JSON spec URL
  swagger-ui:
    path: /swagger-ui.html      # UI URL
    tags-sorter: alpha          # sort tags alphabetically
    operations-sorter: alpha    # sort methods alphabetically
    display-request-duration: true  # show response time
    try-it-out-enabled: true    # enable "Try it out" by default
  show-actuator: false          # hide actuator endpoints
