# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  # stringData = plain text here, K8s encodes to base64 automatically
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: ecommerce_order_management